name: Build Pack
on:
  push:
    branches:
      - master # master 分支 push 时触发工作流
jobs:
  pack: # 打包任务
    runs-on: windows-latest # 在 windows 系统中运行
    steps:
    - uses: actions/checkout@v2 # 下载仓库代码到工作流机器中
    - name: Install and Pack # 安装依赖并且进行构建
      run: |
        npm install
        npm run pack
    - name: Upload file # 将构建产物进行上传
      uses: actions/upload-artifact@v2
      with:
        name: packs # 上传后的名字
        path: packs # 将 packs 目录进行上传
  
