name: Build Pack
on:
  push:
    branches:
      - master 
jobs:
  pack: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macOS-latest] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run pack
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: |
          packs/*dmg # mac 安装包
          packs/*exe # window 安装包
  
